# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_donate.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Donate(object):
    def setupUi(self, Donate):
        Donate.setObjectName("Donate")
        Donate.setWindowModality(QtCore.Qt.WindowModal)
        Donate.setEnabled(True)
        Donate.resize(370, 292)
        Donate.setMinimumSize(QtCore.QSize(370, 292))
        Donate.setMaximumSize(QtCore.QSize(370, 292))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setKerning(True)
        Donate.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Donate.setWindowIcon(icon)
        Donate.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 2px;\n"
"}")
        Donate.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(Donate)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 700))
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(0, 0, 700, 800))
        self.frame_main.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_main.setMaximumSize(QtCore.QSize(16777215, 800))
        self.frame_main.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.toolButton_7 = QtWidgets.QPushButton(self.frame_main)
        self.toolButton_7.setEnabled(True)
        self.toolButton_7.setGeometry(QtCore.QRect(70, 230, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_7.sizePolicy().hasHeightForWidth())
        self.toolButton_7.setSizePolicy(sizePolicy)
        self.toolButton_7.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.toolButton_7.setFont(font)
        self.toolButton_7.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.toolButton_7.setObjectName("toolButton_7")
        self.label_credits_15 = QtWidgets.QLabel(self.frame_main)
        self.label_credits_15.setGeometry(QtCore.QRect(30, 40, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_15.setFont(font)
        self.label_credits_15.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_15.setObjectName("label_credits_15")
        self.toolButton_8 = QtWidgets.QPushButton(self.frame_main)
        self.toolButton_8.setEnabled(True)
        self.toolButton_8.setGeometry(QtCore.QRect(220, 230, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_8.sizePolicy().hasHeightForWidth())
        self.toolButton_8.setSizePolicy(sizePolicy)
        self.toolButton_8.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.toolButton_8.setFont(font)
        self.toolButton_8.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.toolButton_8.setObjectName("toolButton_8")
        self.label_credits_16 = QtWidgets.QLabel(self.frame_main)
        self.label_credits_16.setGeometry(QtCore.QRect(30, 60, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_16.setFont(font)
        self.label_credits_16.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_16.setObjectName("label_credits_16")
        self.label_credits_17 = QtWidgets.QLabel(self.frame_main)
        self.label_credits_17.setGeometry(QtCore.QRect(30, 80, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_17.setFont(font)
        self.label_credits_17.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_17.setObjectName("label_credits_17")
        self.label_credits_18 = QtWidgets.QLabel(self.frame_main)
        self.label_credits_18.setGeometry(QtCore.QRect(30, 100, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_18.setFont(font)
        self.label_credits_18.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_18.setObjectName("label_credits_18")
        self.label_credits_19 = QtWidgets.QLabel(self.frame_main)
        self.label_credits_19.setGeometry(QtCore.QRect(30, 150, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_19.setFont(font)
        self.label_credits_19.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_19.setObjectName("label_credits_19")
        self.label_credits_20 = QtWidgets.QLabel(self.frame_main)
        self.label_credits_20.setGeometry(QtCore.QRect(30, 170, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_20.setFont(font)
        self.label_credits_20.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_20.setObjectName("label_credits_20")
        Donate.setCentralWidget(self.centralwidget)

        self.retranslateUi(Donate)
        QtCore.QMetaObject.connectSlotsByName(Donate)

    def retranslateUi(self, Donate):
        _translate = QtCore.QCoreApplication.translate
        Donate.setWindowTitle(_translate("Donate", "Donate"))
        self.toolButton_7.setText(_translate("Donate", "PayPal"))
        self.label_credits_15.setText(_translate("Donate", "This software is free for personal and commercial use."))
        self.toolButton_8.setText(_translate("Donate", "Bitcoin"))
        self.label_credits_16.setText(_translate("Donate", "It is distributed in the hope that it is useful but without"))
        self.label_credits_17.setText(_translate("Donate", "any warranty. See the GNU General Public Licence v3 "))
        self.label_credits_18.setText(_translate("Donate", "for more information."))
        self.label_credits_19.setText(_translate("Donate", "If you find this application useful, consider making a"))
        self.label_credits_20.setText(_translate("Donate", "donation to support the development. "))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Donate = QtWidgets.QMainWindow()
    ui = Ui_Donate()
    ui.setupUi(Donate)
    Donate.show()
    sys.exit(app.exec_())
