# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(686, 490)
        MainWindow.setMinimumSize(QtCore.QSize(686, 490))
        MainWindow.setMaximumSize(QtCore.QSize(686, 490))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setKerning(True)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/24x24/icons/24x24/cine-encoder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 2px;\n"
"}")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 700))
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(0, 0, 686, 490))
        self.frame_main.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_main.setMaximumSize(QtCore.QSize(16777215, 800))
        self.frame_main.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.layoutWidget = QtWidgets.QWidget(self.frame_main)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 631, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1.setIcon(icon1)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 2, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_1.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 0, 1, 1, 1)
        self.label_credits_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_8.setFont(font)
        self.label_credits_8.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_8.setObjectName("label_credits_8")
        self.gridLayout.addWidget(self.label_credits_8, 0, 0, 1, 1)
        self.frame_top_btns = QtWidgets.QFrame(self.frame_main)
        self.frame_top_btns.setGeometry(QtCore.QRect(0, 0, 686, 30))
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_top_btns.setStyleSheet("background-color: rgba(27, 29, 35, 200)")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        self.frame_btns_right.setGeometry(QtCore.QRect(1070, 0, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btns_right.sizePolicy().hasHeightForWidth())
        self.frame_btns_right.setSizePolicy(sizePolicy)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.actionAbout = QtWidgets.QPushButton(self.frame_top_btns)
        self.actionAbout.setGeometry(QtCore.QRect(5, 0, 40, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionAbout.sizePolicy().hasHeightForWidth())
        self.actionAbout.setSizePolicy(sizePolicy)
        self.actionAbout.setMinimumSize(QtCore.QSize(40, 0))
        self.actionAbout.setMaximumSize(QtCore.QSize(40, 16777215))
        self.actionAbout.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.actionAbout.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-chat-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon2)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDonate = QtWidgets.QPushButton(self.frame_top_btns)
        self.actionDonate.setGeometry(QtCore.QRect(45, 0, 40, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionDonate.sizePolicy().hasHeightForWidth())
        self.actionDonate.setSizePolicy(sizePolicy)
        self.actionDonate.setMinimumSize(QtCore.QSize(40, 0))
        self.actionDonate.setMaximumSize(QtCore.QSize(40, 16777215))
        self.actionDonate.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.actionDonate.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDonate.setIcon(icon3)
        self.actionDonate.setObjectName("actionDonate")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_main)
        self.stackedWidget_2.setGeometry(QtCore.QRect(20, 280, 631, 130))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_0)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 10, 203, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_credits_15 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_15.setFont(font)
        self.label_credits_15.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_15.setObjectName("label_credits_15")
        self.verticalLayout_19.addWidget(self.label_credits_15)
        self.label_credits_16 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_16.setFont(font)
        self.label_credits_16.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_16.setObjectName("label_credits_16")
        self.verticalLayout_19.addWidget(self.label_credits_16)
        self.label_credits_17 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_17.setFont(font)
        self.label_credits_17.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_17.setObjectName("label_credits_17")
        self.verticalLayout_19.addWidget(self.label_credits_17)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.comboBox_1 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_1.setEnabled(True)
        self.comboBox_1.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_1.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_1.setFont(font)
        self.comboBox_1.setAutoFillBackground(False)
        self.comboBox_1.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_1.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_1.setFrame(True)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.verticalLayout_20.addWidget(self.comboBox_1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_3.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_3.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_3.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_3.setFrame(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_20.addWidget(self.comboBox_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_2.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_2.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_2.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.verticalLayout_20.addWidget(self.comboBox_2)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_20)
        self.layoutWidget2 = QtWidgets.QWidget(self.page_0)
        self.layoutWidget2.setGeometry(QtCore.QRect(430, 10, 193, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_credits_18 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_18.setFont(font)
        self.label_credits_18.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_18.setObjectName("label_credits_18")
        self.verticalLayout_21.addWidget(self.label_credits_18)
        self.label_credits_19 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_19.setFont(font)
        self.label_credits_19.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_19.setObjectName("label_credits_19")
        self.verticalLayout_21.addWidget(self.label_credits_19)
        self.label_credits_20 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_20.setFont(font)
        self.label_credits_20.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_20.setObjectName("label_credits_20")
        self.verticalLayout_21.addWidget(self.label_credits_20)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_4.setEnabled(True)
        self.comboBox_4.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_4.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setAutoFillBackground(False)
        self.comboBox_4.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_4.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_4.setFrame(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_22.addWidget(self.comboBox_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_5.setEnabled(True)
        self.comboBox_5.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_5.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setAutoFillBackground(False)
        self.comboBox_5.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_5.setFrame(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_22.addWidget(self.comboBox_5)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_6.setEnabled(True)
        self.comboBox_6.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_6.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setAutoFillBackground(False)
        self.comboBox_6.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_6.setFrame(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_22.addWidget(self.comboBox_6)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_22)
        self.stackedWidget_2.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.layoutWidget_3 = QtWidgets.QWidget(self.page_1)
        self.layoutWidget_3.setGeometry(QtCore.QRect(50, 40, 121, 81))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 7, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_credits_85 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_85.setFont(font)
        self.label_credits_85.setAutoFillBackground(False)
        self.label_credits_85.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_85.setObjectName("label_credits_85")
        self.verticalLayout_4.addWidget(self.label_credits_85)
        self.label_credits_86 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_86.setFont(font)
        self.label_credits_86.setAutoFillBackground(False)
        self.label_credits_86.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_86.setObjectName("label_credits_86")
        self.verticalLayout_4.addWidget(self.label_credits_86)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.layoutWidget_8 = QtWidgets.QWidget(self.page_1)
        self.layoutWidget_8.setGeometry(QtCore.QRect(400, 10, 225, 111))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.formLayout_10 = QtWidgets.QFormLayout(self.layoutWidget_8)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_credits_24 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_24.setFont(font)
        self.label_credits_24.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_24.setObjectName("label_credits_24")
        self.verticalLayout_27.addWidget(self.label_credits_24)
        self.label_credits_25 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_25.setFont(font)
        self.label_credits_25.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_25.setObjectName("label_credits_25")
        self.verticalLayout_27.addWidget(self.label_credits_25)
        self.label_credits_26 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_26.setFont(font)
        self.label_credits_26.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_26.setObjectName("label_credits_26")
        self.verticalLayout_27.addWidget(self.label_credits_26)
        self.formLayout_10.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget_8)
        self.comboBox_9.setEnabled(True)
        self.comboBox_9.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_9.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setAutoFillBackground(False)
        self.comboBox_9.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_9.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_9.setPlaceholderText("")
        self.comboBox_9.setFrame(True)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.verticalLayout_28.addWidget(self.comboBox_9)
        self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget_8)
        self.comboBox_10.setEnabled(True)
        self.comboBox_10.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_10.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setAutoFillBackground(False)
        self.comboBox_10.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_10.setEditable(False)
        self.comboBox_10.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_10.setPlaceholderText("")
        self.comboBox_10.setFrame(True)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.verticalLayout_28.addWidget(self.comboBox_10)
        self.comboBox_11 = QtWidgets.QComboBox(self.layoutWidget_8)
        self.comboBox_11.setEnabled(True)
        self.comboBox_11.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_11.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_11.setFont(font)
        self.comboBox_11.setAutoFillBackground(False)
        self.comboBox_11.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_11.setEditable(False)
        self.comboBox_11.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_11.setPlaceholderText("")
        self.comboBox_11.setFrame(True)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.verticalLayout_28.addWidget(self.comboBox_11)
        self.formLayout_10.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_28)
        self.layoutWidget_9 = QtWidgets.QWidget(self.page_1)
        self.layoutWidget_9.setGeometry(QtCore.QRect(230, 40, 121, 81))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_2.setContentsMargins(0, 7, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_credits_82 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_82.setFont(font)
        self.label_credits_82.setAutoFillBackground(False)
        self.label_credits_82.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_82.setObjectName("label_credits_82")
        self.verticalLayout_3.addWidget(self.label_credits_82)
        self.label_credits_83 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_83.setFont(font)
        self.label_credits_83.setAutoFillBackground(False)
        self.label_credits_83.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_83.setObjectName("label_credits_83")
        self.verticalLayout_3.addWidget(self.label_credits_83)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.comboBox_16 = QtWidgets.QComboBox(self.page_1)
        self.comboBox_16.setEnabled(True)
        self.comboBox_16.setGeometry(QtCore.QRect(220, 11, 130, 30))
        self.comboBox_16.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_16.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_16.setFont(font)
        self.comboBox_16.setAutoFillBackground(False)
        self.comboBox_16.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_16.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_16.setPlaceholderText("")
        self.comboBox_16.setFrame(True)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.label_credits_27 = QtWidgets.QLabel(self.page_1)
        self.label_credits_27.setGeometry(QtCore.QRect(130, 11, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_27.setFont(font)
        self.label_credits_27.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_27.setObjectName("label_credits_27")
        self.stackedWidget_2.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(250, 35, 371, 81))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_credits_90 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_90.setFont(font)
        self.label_credits_90.setAutoFillBackground(False)
        self.label_credits_90.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_90.setObjectName("label_credits_90")
        self.verticalLayout_6.addWidget(self.label_credits_90)
        self.label_credits_92 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_92.setFont(font)
        self.label_credits_92.setAutoFillBackground(False)
        self.label_credits_92.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_92.setObjectName("label_credits_92")
        self.verticalLayout_6.addWidget(self.label_credits_92)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_5.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_5.addWidget(self.lineEdit_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.comboBox_15 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_15.setEnabled(True)
        self.comboBox_15.setGeometry(QtCore.QRect(490, 0, 130, 30))
        self.comboBox_15.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_15.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.comboBox_15.setFont(font)
        self.comboBox_15.setAutoFillBackground(False)
        self.comboBox_15.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_15.setEditable(False)
        self.comboBox_15.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_15.setPlaceholderText("")
        self.comboBox_15.setFrame(True)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.label_credits_59 = QtWidgets.QLabel(self.page_2)
        self.label_credits_59.setGeometry(QtCore.QRect(390, 0, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_59.setFont(font)
        self.label_credits_59.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_59.setObjectName("label_credits_59")
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.layoutWidget4 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(420, 10, 200, 109))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout_9 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_credits_43 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_43.setFont(font)
        self.label_credits_43.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_43.setObjectName("label_credits_43")
        self.verticalLayout_31.addWidget(self.label_credits_43)
        self.label_credits_44 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_44.setFont(font)
        self.label_credits_44.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_44.setObjectName("label_credits_44")
        self.verticalLayout_31.addWidget(self.label_credits_44)
        self.label_credits_45 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_45.setFont(font)
        self.label_credits_45.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_45.setObjectName("label_credits_45")
        self.verticalLayout_31.addWidget(self.label_credits_45)
        self.formLayout_9.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_31)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.comboBox_12 = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox_12.setEnabled(True)
        self.comboBox_12.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_12.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_12.setFont(font)
        self.comboBox_12.setAutoFillBackground(False)
        self.comboBox_12.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_12.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_12.setFrame(True)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.verticalLayout_32.addWidget(self.comboBox_12)
        self.comboBox_14 = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox_14.setEnabled(True)
        self.comboBox_14.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_14.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_14.setFont(font)
        self.comboBox_14.setAutoFillBackground(False)
        self.comboBox_14.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_14.setEditable(False)
        self.comboBox_14.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_14.setFrame(True)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.verticalLayout_32.addWidget(self.comboBox_14)
        self.comboBox_13 = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox_13.setEnabled(True)
        self.comboBox_13.setMinimumSize(QtCore.QSize(130, 30))
        self.comboBox_13.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_13.setFont(font)
        self.comboBox_13.setAutoFillBackground(False)
        self.comboBox_13.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_13.setEditable(False)
        self.comboBox_13.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_13.setFrame(True)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.verticalLayout_32.addWidget(self.comboBox_13)
        self.formLayout_9.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_32)
        self.stackedWidget_2.addWidget(self.page_3)
        self.stackedWidget_1 = QtWidgets.QStackedWidget(self.frame_main)
        self.stackedWidget_1.setGeometry(QtCore.QRect(10, 100, 641, 130))
        self.stackedWidget_1.setObjectName("stackedWidget_1")
        self.page_01 = QtWidgets.QWidget()
        self.page_01.setObjectName("page_01")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_01)
        self.layoutWidget_2.setGeometry(QtCore.QRect(60, 10, 201, 106))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setVerticalSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_fcredits_12 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_fcredits_12.setFont(font)
        self.label_fcredits_12.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_fcredits_12.setObjectName("label_fcredits_12")
        self.verticalLayout_16.addWidget(self.label_fcredits_12)
        self.label_credits_14 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_14.setFont(font)
        self.label_credits_14.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_14.setObjectName("label_credits_14")
        self.verticalLayout_16.addWidget(self.label_credits_14)
        self.label_credits_30 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_credits_30.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_30.setFont(font)
        self.label_credits_30.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_30.setObjectName("label_credits_30")
        self.verticalLayout_16.addWidget(self.label_credits_30)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_format = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_format.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_format.setFont(font)
        self.label_format.setObjectName("label_format")
        self.verticalLayout_17.addWidget(self.label_format)
        self.label_duration = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_duration.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_duration.setFont(font)
        self.label_duration.setObjectName("label_duration")
        self.verticalLayout_17.addWidget(self.label_duration)
        self.label_resolution = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_resolution.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_resolution.setFont(font)
        self.label_resolution.setObjectName("label_resolution")
        self.verticalLayout_17.addWidget(self.label_resolution)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_17)
        self.layoutWidget_5 = QtWidgets.QWidget(self.page_01)
        self.layoutWidget_5.setGeometry(QtCore.QRect(280, 10, 191, 106))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.formLayout_8 = QtWidgets.QFormLayout(self.layoutWidget_5)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_credits_39 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_39.setFont(font)
        self.label_credits_39.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_39.setObjectName("label_credits_39")
        self.verticalLayout_25.addWidget(self.label_credits_39)
        self.label_credits_40 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_40.setFont(font)
        self.label_credits_40.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_40.setObjectName("label_credits_40")
        self.verticalLayout_25.addWidget(self.label_credits_40)
        self.label_credits_41 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_41.setFont(font)
        self.label_credits_41.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_41.setObjectName("label_credits_41")
        self.verticalLayout_25.addWidget(self.label_credits_41)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_25)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_subsampling = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_subsampling.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_subsampling.setFont(font)
        self.label_subsampling.setObjectName("label_subsampling")
        self.verticalLayout_26.addWidget(self.label_subsampling)
        self.label_bitrate = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_bitrate.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_bitrate.setFont(font)
        self.label_bitrate.setObjectName("label_bitrate")
        self.verticalLayout_26.addWidget(self.label_bitrate)
        self.label_fps = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_fps.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_fps.setFont(font)
        self.label_fps.setObjectName("label_fps")
        self.verticalLayout_26.addWidget(self.label_fps)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_26)
        self.layoutWidget_4 = QtWidgets.QWidget(self.page_01)
        self.layoutWidget_4.setGeometry(QtCore.QRect(490, 10, 151, 106))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.formLayout_7 = QtWidgets.QFormLayout(self.layoutWidget_4)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_credits_33 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_33.setFont(font)
        self.label_credits_33.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_33.setObjectName("label_credits_33")
        self.verticalLayout_23.addWidget(self.label_credits_33)
        self.label_credits_34 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_34.setFont(font)
        self.label_credits_34.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_34.setObjectName("label_credits_34")
        self.verticalLayout_23.addWidget(self.label_credits_34)
        self.label_credits_35 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_35.setFont(font)
        self.label_credits_35.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_35.setObjectName("label_credits_35")
        self.verticalLayout_23.addWidget(self.label_credits_35)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_aspect_ratio = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_aspect_ratio.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_aspect_ratio.setFont(font)
        self.label_aspect_ratio.setObjectName("label_aspect_ratio")
        self.verticalLayout_24.addWidget(self.label_aspect_ratio)
        self.label_color_space = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_color_space.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_color_space.setFont(font)
        self.label_color_space.setObjectName("label_color_space")
        self.verticalLayout_24.addWidget(self.label_color_space)
        self.label_bit_depth = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_bit_depth.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_bit_depth.setFont(font)
        self.label_bit_depth.setObjectName("label_bit_depth")
        self.verticalLayout_24.addWidget(self.label_bit_depth)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_24)
        self.stackedWidget_1.addWidget(self.page_01)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.layoutWidget_6 = QtWidgets.QWidget(self.page_11)
        self.layoutWidget_6.setGeometry(QtCore.QRect(60, 10, 181, 106))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.layoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setVerticalSpacing(6)
        self.formLayout_6.setObjectName("formLayout_6")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_credits_13 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_13.setFont(font)
        self.label_credits_13.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_13.setObjectName("label_credits_13")
        self.verticalLayout_18.addWidget(self.label_credits_13)
        self.label_credits_22 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_22.setFont(font)
        self.label_credits_22.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_22.setObjectName("label_credits_22")
        self.verticalLayout_18.addWidget(self.label_credits_22)
        self.label_credits_32 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_credits_32.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_32.setFont(font)
        self.label_credits_32.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_32.setObjectName("label_credits_32")
        self.verticalLayout_18.addWidget(self.label_credits_32)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_18)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_audio_1 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_audio_1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_audio_1.setFont(font)
        self.label_audio_1.setText("")
        self.label_audio_1.setObjectName("label_audio_1")
        self.verticalLayout_29.addWidget(self.label_audio_1)
        self.label_audio_2 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_audio_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_audio_2.setFont(font)
        self.label_audio_2.setText("")
        self.label_audio_2.setObjectName("label_audio_2")
        self.verticalLayout_29.addWidget(self.label_audio_2)
        self.label_audio_3 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_audio_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_audio_3.setFont(font)
        self.label_audio_3.setText("")
        self.label_audio_3.setObjectName("label_audio_3")
        self.verticalLayout_29.addWidget(self.label_audio_3)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_29)
        self.layoutWidget_7 = QtWidgets.QWidget(self.page_11)
        self.layoutWidget_7.setGeometry(QtCore.QRect(290, 10, 171, 106))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.formLayout_11 = QtWidgets.QFormLayout(self.layoutWidget_7)
        self.formLayout_11.setContentsMargins(0, 0, 0, 0)
        self.formLayout_11.setVerticalSpacing(6)
        self.formLayout_11.setObjectName("formLayout_11")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_credits_29 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_29.setFont(font)
        self.label_credits_29.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_29.setObjectName("label_credits_29")
        self.verticalLayout_30.addWidget(self.label_credits_29)
        self.label_credits_50 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_50.setFont(font)
        self.label_credits_50.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_50.setObjectName("label_credits_50")
        self.verticalLayout_30.addWidget(self.label_credits_50)
        self.label_credits_51 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_credits_51.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_51.setFont(font)
        self.label_credits_51.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_51.setObjectName("label_credits_51")
        self.verticalLayout_30.addWidget(self.label_credits_51)
        self.formLayout_11.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_30)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_audio_4 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_audio_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_audio_4.setFont(font)
        self.label_audio_4.setText("")
        self.label_audio_4.setObjectName("label_audio_4")
        self.verticalLayout_33.addWidget(self.label_audio_4)
        self.label_audio_5 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_audio_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_audio_5.setFont(font)
        self.label_audio_5.setText("")
        self.label_audio_5.setObjectName("label_audio_5")
        self.verticalLayout_33.addWidget(self.label_audio_5)
        self.label_audio_6 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_audio_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_audio_6.setFont(font)
        self.label_audio_6.setText("")
        self.label_audio_6.setObjectName("label_audio_6")
        self.verticalLayout_33.addWidget(self.label_audio_6)
        self.formLayout_11.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_33)
        self.layoutWidget_10 = QtWidgets.QWidget(self.page_11)
        self.layoutWidget_10.setGeometry(QtCore.QRect(500, 10, 141, 106))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.formLayout_13 = QtWidgets.QFormLayout(self.layoutWidget_10)
        self.formLayout_13.setContentsMargins(0, 0, 0, 0)
        self.formLayout_13.setVerticalSpacing(6)
        self.formLayout_13.setObjectName("formLayout_13")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_credits_48 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_48.setFont(font)
        self.label_credits_48.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_48.setObjectName("label_credits_48")
        self.verticalLayout_36.addWidget(self.label_credits_48)
        self.label_credits_55 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_55.setFont(font)
        self.label_credits_55.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_55.setObjectName("label_credits_55")
        self.verticalLayout_36.addWidget(self.label_credits_55)
        self.label_credits_56 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_credits_56.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_56.setFont(font)
        self.label_credits_56.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_56.setObjectName("label_credits_56")
        self.verticalLayout_36.addWidget(self.label_credits_56)
        self.formLayout_13.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_36)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_audio_7 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_audio_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_audio_7.setFont(font)
        self.label_audio_7.setText("")
        self.label_audio_7.setObjectName("label_audio_7")
        self.verticalLayout_37.addWidget(self.label_audio_7)
        self.label_audio_8 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_audio_8.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_audio_8.setFont(font)
        self.label_audio_8.setText("")
        self.label_audio_8.setObjectName("label_audio_8")
        self.verticalLayout_37.addWidget(self.label_audio_8)
        self.label_audio_9 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_audio_9.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_audio_9.setFont(font)
        self.label_audio_9.setText("")
        self.label_audio_9.setObjectName("label_audio_9")
        self.verticalLayout_37.addWidget(self.label_audio_9)
        self.formLayout_13.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_37)
        self.stackedWidget_1.addWidget(self.page_11)
        self.frame_top_btns_2 = QtWidgets.QFrame(self.frame_main)
        self.frame_top_btns_2.setGeometry(QtCore.QRect(0, 450, 686, 40))
        self.frame_top_btns_2.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_top_btns_2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_top_btns_2.setStyleSheet("background-color: rgba(27, 29, 35, 200)")
        self.frame_top_btns_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns_2.setObjectName("frame_top_btns_2")
        self.frame_btns_right_3 = QtWidgets.QFrame(self.frame_top_btns_2)
        self.frame_btns_right_3.setGeometry(QtCore.QRect(1070, 0, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btns_right_3.sizePolicy().hasHeightForWidth())
        self.frame_btns_right_3.setSizePolicy(sizePolicy)
        self.frame_btns_right_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right_3.setObjectName("frame_btns_right_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_btns_right_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_top_btns_2)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 5, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_top_btns_2)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 5, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_53 = QtWidgets.QLabel(self.frame_top_btns_2)
        self.label_53.setEnabled(True)
        self.label_53.setGeometry(QtCore.QRect(21, 12, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_53.setFont(font)
        self.label_53.setAutoFillBackground(False)
        self.label_53.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_53.setObjectName("label_53")
        self.progressBar = QtWidgets.QProgressBar(self.frame_top_btns_2)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(82, 10, 241, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.progressBar.setAcceptDrops(False)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.label_54 = QtWidgets.QLabel(self.frame_top_btns_2)
        self.label_54.setGeometry(QtCore.QRect(340, 12, 65, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_54.setFont(font)
        self.label_54.setAutoFillBackground(False)
        self.label_54.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.frame_top_btns_2)
        self.label_55.setGeometry(QtCore.QRect(410, 12, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_55.setFont(font)
        self.label_55.setAutoFillBackground(False)
        self.label_55.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_55.setObjectName("label_55")
        self.layoutWidget5 = QtWidgets.QWidget(self.frame_main)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 230, 631, 32))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_credits_9 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits_9.setFont(font)
        self.label_credits_9.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits_9.setObjectName("label_credits_9")
        self.horizontalLayout.addWidget(self.label_credits_9)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.turnLeftStack_2 = QtWidgets.QPushButton(self.frame_main)
        self.turnLeftStack_2.setGeometry(QtCore.QRect(650, 280, 10, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turnLeftStack_2.sizePolicy().hasHeightForWidth())
        self.turnLeftStack_2.setSizePolicy(sizePolicy)
        self.turnLeftStack_2.setMinimumSize(QtCore.QSize(0, 0))
        self.turnLeftStack_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.turnLeftStack_2.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.turnLeftStack_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-arrow-left-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.turnLeftStack_2.setIcon(icon4)
        self.turnLeftStack_2.setIconSize(QtCore.QSize(14, 14))
        self.turnLeftStack_2.setObjectName("turnLeftStack_2")
        self.turnRightStack_2 = QtWidgets.QPushButton(self.frame_main)
        self.turnRightStack_2.setGeometry(QtCore.QRect(665, 280, 10, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turnRightStack_2.sizePolicy().hasHeightForWidth())
        self.turnRightStack_2.setSizePolicy(sizePolicy)
        self.turnRightStack_2.setMinimumSize(QtCore.QSize(0, 0))
        self.turnRightStack_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.turnRightStack_2.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.turnRightStack_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-arrow-right-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.turnRightStack_2.setIcon(icon5)
        self.turnRightStack_2.setIconSize(QtCore.QSize(14, 14))
        self.turnRightStack_2.setObjectName("turnRightStack_2")
        self.turnRightStack_1 = QtWidgets.QPushButton(self.frame_main)
        self.turnRightStack_1.setGeometry(QtCore.QRect(665, 100, 10, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turnRightStack_1.sizePolicy().hasHeightForWidth())
        self.turnRightStack_1.setSizePolicy(sizePolicy)
        self.turnRightStack_1.setMinimumSize(QtCore.QSize(0, 0))
        self.turnRightStack_1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.turnRightStack_1.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.turnRightStack_1.setText("")
        self.turnRightStack_1.setIcon(icon5)
        self.turnRightStack_1.setIconSize(QtCore.QSize(14, 14))
        self.turnRightStack_1.setObjectName("turnRightStack_1")
        self.turnLeftStack_1 = QtWidgets.QPushButton(self.frame_main)
        self.turnLeftStack_1.setGeometry(QtCore.QRect(650, 100, 10, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turnLeftStack_1.sizePolicy().hasHeightForWidth())
        self.turnLeftStack_1.setSizePolicy(sizePolicy)
        self.turnLeftStack_1.setMinimumSize(QtCore.QSize(0, 0))
        self.turnLeftStack_1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.turnLeftStack_1.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.turnLeftStack_1.setText("")
        self.turnLeftStack_1.setIcon(icon4)
        self.turnLeftStack_1.setIconSize(QtCore.QSize(14, 14))
        self.turnLeftStack_1.setObjectName("turnLeftStack_1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cine Encoder 2020 SE"))
        self.pushButton_1.setText(_translate("MainWindow", "Select"))
        self.lineEdit_1.setPlaceholderText(_translate("MainWindow", "Select input file"))
        self.label_credits_8.setText(_translate("MainWindow", "Source:"))
        self.actionAbout.setToolTip(_translate("MainWindow", "Minimize"))
        self.actionDonate.setToolTip(_translate("MainWindow", "Minimize"))
        self.label_credits_15.setText(_translate("MainWindow", "Codec:"))
        self.label_credits_16.setText(_translate("MainWindow", "Hardware:"))
        self.label_credits_17.setText(_translate("MainWindow", "Format:"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "H265  10 bit"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "VP9  10 bit"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "AV1  10 bit"))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "H265  8 bit"))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "H264  8 bit"))
        self.comboBox_1.setItemText(5, _translate("MainWindow", "ProRes HQ"))
        self.comboBox_1.setItemText(6, _translate("MainWindow", "DNxHR HQX"))
        self.comboBox_1.setItemText(7, _translate("MainWindow", "From source"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "CPU"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "NVENC"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "MKV"))
        self.label_credits_18.setText(_translate("MainWindow", "Mode:"))
        self.label_credits_19.setText(_translate("MainWindow", "Bitrate:"))
        self.label_credits_20.setText(_translate("MainWindow", "Maxrate:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "VBR"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "CQP"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "45M"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "60M"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "50M"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "40M"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "30M"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "20M"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "10M"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "50M"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "70M"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "60M"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "50M"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "40M"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "30M"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "20M"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "10M"))
        self.label_credits_85.setText(_translate("MainWindow", "Max lum:"))
        self.label_credits_86.setText(_translate("MainWindow", "Min lum:"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "None"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "None"))
        self.label_credits_24.setText(_translate("MainWindow", "Color prim:"))
        self.label_credits_25.setText(_translate("MainWindow", "Color matrix:"))
        self.label_credits_26.setText(_translate("MainWindow", "Transfer:"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "None"))
        self.label_credits_82.setText(_translate("MainWindow", "Max cll:"))
        self.label_credits_83.setText(_translate("MainWindow", "Max fall:"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "None"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "None"))
        self.comboBox_16.setCurrentText(_translate("MainWindow", "None"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "None"))
        self.label_credits_27.setText(_translate("MainWindow", "Color range:"))
        self.label_credits_90.setText(_translate("MainWindow", "Chromaticity coordinates:"))
        self.label_credits_92.setText(_translate("MainWindow", "White color coordinates:"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "None"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "None"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "None"))
        self.label_credits_59.setText(_translate("MainWindow", "Master display:"))
        self.label_credits_43.setText(_translate("MainWindow", "Audio:"))
        self.label_credits_44.setText(_translate("MainWindow", "Sampling:"))
        self.label_credits_45.setText(_translate("MainWindow", "Bitrate:"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "From source"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "AAC"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "AC3"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "Auto"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "From source"))
        self.label_fcredits_12.setText(_translate("MainWindow", "Format:"))
        self.label_credits_14.setText(_translate("MainWindow", "Duration: "))
        self.label_credits_30.setText(_translate("MainWindow", "Resolution:"))
        self.label_format.setText(_translate("MainWindow", "n/a"))
        self.label_duration.setText(_translate("MainWindow", "n/a"))
        self.label_resolution.setText(_translate("MainWindow", "n/a"))
        self.label_credits_39.setText(_translate("MainWindow", "Subsampling:"))
        self.label_credits_40.setText(_translate("MainWindow", "Bitrate:"))
        self.label_credits_41.setText(_translate("MainWindow", "Frame rate:"))
        self.label_subsampling.setText(_translate("MainWindow", "n/a"))
        self.label_bitrate.setText(_translate("MainWindow", "n/a"))
        self.label_fps.setText(_translate("MainWindow", "n/a"))
        self.label_credits_33.setText(_translate("MainWindow", "Aspect ratio:"))
        self.label_credits_34.setText(_translate("MainWindow", "Color space:"))
        self.label_credits_35.setText(_translate("MainWindow", "Bit depth:"))
        self.label_aspect_ratio.setText(_translate("MainWindow", "n/a"))
        self.label_color_space.setText(_translate("MainWindow", "n/a"))
        self.label_bit_depth.setText(_translate("MainWindow", "n/a"))
        self.label_credits_13.setText(_translate("MainWindow", "Audio #1:"))
        self.label_credits_22.setText(_translate("MainWindow", "Audio #2:"))
        self.label_credits_32.setText(_translate("MainWindow", "Audio #3:"))
        self.label_credits_29.setText(_translate("MainWindow", "Audio #4:"))
        self.label_credits_50.setText(_translate("MainWindow", "Audio #5:"))
        self.label_credits_51.setText(_translate("MainWindow", "Audio #6:"))
        self.label_credits_48.setText(_translate("MainWindow", "Audio #7:"))
        self.label_credits_55.setText(_translate("MainWindow", "Audio #8:"))
        self.label_credits_56.setText(_translate("MainWindow", "Audio #9:"))
        self.pushButton_3.setText(_translate("MainWindow", "Encode"))
        self.pushButton_4.setText(_translate("MainWindow", "Stop"))
        self.label_53.setText(_translate("MainWindow", "Progress:"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.label_54.setText(_translate("MainWindow", "Remaining:"))
        self.label_55.setText(_translate("MainWindow", "00:00:00"))
        self.label_credits_9.setText(_translate("MainWindow", "Output:"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Select output file"))
        self.pushButton_2.setText(_translate("MainWindow", "Select"))
        self.turnLeftStack_2.setToolTip(_translate("MainWindow", "Minimize"))
        self.turnRightStack_2.setToolTip(_translate("MainWindow", "Minimize"))
        self.turnRightStack_1.setToolTip(_translate("MainWindow", "Minimize"))
        self.turnLeftStack_1.setToolTip(_translate("MainWindow", "Minimize"))
        self.label_53.hide() # (add to ui_main)
        self.label_54.hide() # (add to ui_main)
        self.label_55.hide() # (add to ui_main)
        self.progressBar.hide() # (add to ui_main)
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
