#############################################################################
# Makefile for building: cine_encoder
# Generated by qmake (3.1) (Qt 5.15.1)
# Project:  ../cine-encoder-3.0/app/cine_encoder.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile ../cine-encoder-3.0/app/cine_encoder.pro -spec linux-g++ CONFIG+=debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../cine-encoder-3.0/app -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cine_encoder1.0.0
DISTDIR = /run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/build-cine_encoder-Desktop-Debug/.tmp/cine_encoder1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lmediainfo /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../cine-encoder-3.0/app/about.cpp \
		../cine-encoder-3.0/app/main.cpp \
		../cine-encoder-3.0/app/mainwindow.cpp \
		../cine-encoder-3.0/app/preset.cpp \
		../cine-encoder-3.0/app/selectpreset.cpp \
		../cine-encoder-3.0/app/settings.cpp \
		../cine-encoder-3.0/app/taskcomplete.cpp qrc_files.cpp \
		moc_about.cpp \
		moc_mainwindow.cpp \
		moc_preset.cpp \
		moc_selectpreset.cpp \
		moc_settings.cpp \
		moc_taskcomplete.cpp
OBJECTS       = about.o \
		main.o \
		mainwindow.o \
		preset.o \
		selectpreset.o \
		settings.o \
		taskcomplete.o \
		qrc_files.o \
		moc_about.o \
		moc_mainwindow.o \
		moc_preset.o \
		moc_selectpreset.o \
		moc_settings.o \
		moc_taskcomplete.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		../cine-encoder-3.0/app/.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		../cine-encoder-3.0/cine-encoder-3.0/app/cine_encoder.pro ../cine-encoder-3.0/app/about.h \
		../cine-encoder-3.0/app/mainwindow.h \
		../cine-encoder-3.0/app/preset.h \
		../cine-encoder-3.0/app/selectpreset.h \
		../cine-encoder-3.0/app/settings.h \
		../cine-encoder-3.0/app/taskcomplete.h ../cine-encoder-3.0/app/about.cpp \
		../cine-encoder-3.0/app/main.cpp \
		../cine-encoder-3.0/app/mainwindow.cpp \
		../cine-encoder-3.0/app/preset.cpp \
		../cine-encoder-3.0/app/selectpreset.cpp \
		../cine-encoder-3.0/app/settings.cpp \
		../cine-encoder-3.0/app/taskcomplete.cpp
QMAKE_TARGET  = cine_encoder
DESTDIR       = 
TARGET        = cine_encoder


first: all
####### Build rules

cine_encoder: ui_about.h ui_mainwindow.h ui_preset.h ui_selectpreset.h ui_settings.h ui_taskcomplete.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../cine-encoder-3.0/app/cine_encoder.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		../cine-encoder-3.0/app/cine_encoder.pro \
		../cine-encoder-3.0/app/files.qrc
	$(QMAKE) -o Makefile ../cine-encoder-3.0/app/cine_encoder.pro -spec linux-g++ CONFIG+=debug
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCddb.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_repparser.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scxml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
../cine-encoder-3.0/app/cine_encoder.pro:
../cine-encoder-3.0/app/files.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile ../cine-encoder-3.0/app/cine_encoder.pro -spec linux-g++ CONFIG+=debug

qmake_all: FORCE


all: Makefile cine_encoder

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../cine-encoder-3.0/app/files.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../cine-encoder-3.0/app/about.h ../cine-encoder-3.0/app/mainwindow.h ../cine-encoder-3.0/app/preset.h ../cine-encoder-3.0/app/selectpreset.h ../cine-encoder-3.0/app/settings.h ../cine-encoder-3.0/app/taskcomplete.h $(DISTDIR)/
	$(COPY_FILE) --parents ../cine-encoder-3.0/app/about.cpp ../cine-encoder-3.0/app/main.cpp ../cine-encoder-3.0/app/mainwindow.cpp ../cine-encoder-3.0/app/preset.cpp ../cine-encoder-3.0/app/selectpreset.cpp ../cine-encoder-3.0/app/settings.cpp ../cine-encoder-3.0/app/taskcomplete.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../cine-encoder-3.0/app/about.ui ../cine-encoder-3.0/app/mainwindow.ui ../cine-encoder-3.0/app/preset.ui ../cine-encoder-3.0/app/selectpreset.ui ../cine-encoder-3.0/app/settings.ui ../cine-encoder-3.0/app/taskcomplete.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_files.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_files.cpp
qrc_files.cpp: ../cine-encoder-3.0/app/files.qrc \
		/usr/bin/rcc \
		../cine-encoder-3.0/app/icons/16x16/cil-text-square.png \
		../cine-encoder-3.0/app/icons/16x16/cil-volume-high.png \
		../cine-encoder-3.0/app/icons/16x16/cil-window-restore.png \
		../cine-encoder-3.0/app/icons/16x16/cil-media-play.png \
		../cine-encoder-3.0/app/icons/16x16/cil-image-plus.png \
		../cine-encoder-3.0/app/icons/16x16/cil-rectangle.png \
		../cine-encoder-3.0/app/icons/16x16/cil-signal-cellular-0.png \
		../cine-encoder-3.0/app/icons/16x16/cil-lightbulb.png \
		../cine-encoder-3.0/app/icons/16x16/cil-library.png \
		../cine-encoder-3.0/app/icons/16x16/cil-voice-over-record.png \
		../cine-encoder-3.0/app/icons/16x16/cil-arrow-top.png \
		../cine-encoder-3.0/app/icons/16x16/cil-people.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chevron-right.png \
		../cine-encoder-3.0/app/icons/16x16/cil-paint-bucket.png \
		../cine-encoder-3.0/app/icons/16x16/cil-cart.png \
		../cine-encoder-3.0/app/icons/16x16/cil-folder-open.png \
		../cine-encoder-3.0/app/icons/16x16/cil-map.png \
		../cine-encoder-3.0/app/icons/16x16/cil-input.png \
		../cine-encoder-3.0/app/icons/16x16/cil-4k.png \
		../cine-encoder-3.0/app/icons/16x16/cil-pin.png \
		../cine-encoder-3.0/app/icons/16x16/cil-check-circle.png \
		../cine-encoder-3.0/app/icons/16x16/cil-plus.png \
		../cine-encoder-3.0/app/icons/16x16/cil-drop.png \
		../cine-encoder-3.0/app/icons/16x16/cil-caret-left.png \
		../cine-encoder-3.0/app/icons/16x16/cil-terminal.png \
		../cine-encoder-3.0/app/icons/16x16/cil-check-alt.png \
		../cine-encoder-3.0/app/icons/16x16/cil-media-eject.png \
		../cine-encoder-3.0/app/icons/16x16/cil-caret-bottom.png \
		../cine-encoder-3.0/app/icons/16x16/cil-magnifying-glass.png \
		../cine-encoder-3.0/app/icons/16x16/cil-screen-smartphone.png \
		../cine-encoder-3.0/app/icons/16x16/cil-user-unfollow.png \
		../cine-encoder-3.0/app/icons/16x16/cil-circle.png \
		../cine-encoder-3.0/app/icons/16x16/cil-cloud-download.png \
		../cine-encoder-3.0/app/icons/16x16/cil-clone.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chevron-double-left.png \
		../cine-encoder-3.0/app/icons/16x16/cil-action-undo.png \
		../cine-encoder-3.0/app/icons/16x16/cil-reload.png \
		../cine-encoder-3.0/app/icons/16x16/cil-window-minimize.png \
		../cine-encoder-3.0/app/icons/16x16/cil-zoom-in.png \
		../cine-encoder-3.0/app/icons/16x16/cil-bell.png \
		../cine-encoder-3.0/app/icons/16x16/cil-folder.png \
		../cine-encoder-3.0/app/icons/16x16/cil-cursor.png \
		../cine-encoder-3.0/app/icons/16x16/cil-layers.png \
		../cine-encoder-3.0/app/icons/16x16/cil-menu.png \
		../cine-encoder-3.0/app/icons/16x16/cil-expand-left.png \
		../cine-encoder-3.0/app/icons/16x16/cil-library-add.png \
		../cine-encoder-3.0/app/icons/16x16/cil-action-redo.png \
		../cine-encoder-3.0/app/icons/16x16/cil-microphone.png \
		../cine-encoder-3.0/app/icons/16x16/cil-calendar-check.png \
		../cine-encoder-3.0/app/icons/16x16/cil-link.png \
		../cine-encoder-3.0/app/icons/16x16/cil-options-horizontal.png \
		../cine-encoder-3.0/app/icons/16x16/cil-media-step-forward.png \
		../cine-encoder-3.0/app/icons/16x16/cil-level-down.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chevron-double-down.png \
		../cine-encoder-3.0/app/icons/16x16/cil-task.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chevron-double-right.png \
		../cine-encoder-3.0/app/icons/16x16/cil-account-logout.png \
		../cine-encoder-3.0/app/icons/16x16/cil-exposure.png \
		../cine-encoder-3.0/app/icons/16x16/cil-expand-down.png \
		../cine-encoder-3.0/app/icons/16x16/cil-alarm.png \
		../cine-encoder-3.0/app/icons/16x16/cil-tags.png \
		../cine-encoder-3.0/app/icons/16x16/cil-vertical-align-bottom.png \
		../cine-encoder-3.0/app/icons/16x16/cil-edit.png \
		../cine-encoder-3.0/app/icons/16x16/cil-ban.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chevron-double-up.png \
		../cine-encoder-3.0/app/icons/16x16/cil-speaker.png \
		../cine-encoder-3.0/app/icons/16x16/cil-cut.png \
		../cine-encoder-3.0/app/icons/16x16/cil-history.png \
		../cine-encoder-3.0/app/icons/16x16/cil-comment-bubble.png \
		../cine-encoder-3.0/app/icons/16x16/cil-loop.png \
		../cine-encoder-3.0/app/icons/16x16/cil-infinity.png \
		../cine-encoder-3.0/app/icons/16x16/cil-volume-off.png \
		../cine-encoder-3.0/app/icons/16x16/cil-power-standby.png \
		../cine-encoder-3.0/app/icons/16x16/cil-text-size.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chart-line.png \
		../cine-encoder-3.0/app/icons/16x16/cil-mobile-landscape.png \
		../cine-encoder-3.0/app/icons/16x16/cil-mug-tea.png \
		../cine-encoder-3.0/app/icons/16x16/cil-notes.png \
		../cine-encoder-3.0/app/icons/16x16/cil-location-pin.png \
		../cine-encoder-3.0/app/icons/16x16/cil-find-in-page.png \
		../cine-encoder-3.0/app/icons/16x16/cil-3d.png \
		../cine-encoder-3.0/app/icons/16x16/cil-level-up.png \
		../cine-encoder-3.0/app/icons/16x16/cil-arrow-bottom.png \
		../cine-encoder-3.0/app/icons/16x16/cil-user-female.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chart.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chevron-bottom.png \
		../cine-encoder-3.0/app/icons/16x16/cil-star.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chevron-left.png \
		../cine-encoder-3.0/app/icons/16x16/cil-minus.png \
		../cine-encoder-3.0/app/icons/16x16/cil-mug.png \
		../cine-encoder-3.0/app/icons/16x16/cil-link-alt.png \
		../cine-encoder-3.0/app/icons/16x16/cil-expand-right.png \
		../cine-encoder-3.0/app/icons/16x16/cil-media-skip-forward.png \
		../cine-encoder-3.0/app/icons/16x16/cil-volume-low.png \
		../cine-encoder-3.0/app/icons/16x16/cil-mobile.png \
		../cine-encoder-3.0/app/icons/16x16/cil-loop-1.png \
		../cine-encoder-3.0/app/icons/16x16/cil-signal-cellular-3.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chevron-double-up-alt.png \
		../cine-encoder-3.0/app/icons/16x16/cil-arrow-left-.png \
		../cine-encoder-3.0/app/icons/16x16/cil-wrap-text.png \
		../cine-encoder-3.0/app/icons/16x16/cil-pencil.png \
		../cine-encoder-3.0/app/icons/16x16/cil-code.png \
		../cine-encoder-3.0/app/icons/16x16/cil-file.png \
		../cine-encoder-3.0/app/icons/16x16/cil-media-pause.png \
		../cine-encoder-3.0/app/icons/16x16/cil-triangle.png \
		../cine-encoder-3.0/app/icons/16x16/cil-lock-locked.png \
		../cine-encoder-3.0/app/icons/16x16/cil-user-follow.png \
		../cine-encoder-3.0/app/icons/16x16/cil-coffee.png \
		../cine-encoder-3.0/app/icons/16x16/cil-x-circle.png \
		../cine-encoder-3.0/app/icons/16x16/cil-share.png \
		../cine-encoder-3.0/app/icons/16x16/cil-speech.png \
		../cine-encoder-3.0/app/icons/16x16/cil-hd.png \
		../cine-encoder-3.0/app/icons/16x16/cil-speedometer.png \
		../cine-encoder-3.0/app/icons/16x16/cil-clipboard.png \
		../cine-encoder-3.0/app/icons/16x16/cil-home.png \
		../cine-encoder-3.0/app/icons/16x16/cil-loop-circular.png \
		../cine-encoder-3.0/app/icons/16x16/cil-share-boxed.png \
		../cine-encoder-3.0/app/icons/16x16/cil-link-broken.png \
		../cine-encoder-3.0/app/icons/16x16/cil-flip-to-back.png \
		../cine-encoder-3.0/app/icons/16x16/cil-transfer.png \
		../cine-encoder-3.0/app/icons/16x16/cil-house.png \
		../cine-encoder-3.0/app/icons/16x16/cil-image1.png \
		../cine-encoder-3.0/app/icons/16x16/cil-caret-right.png \
		../cine-encoder-3.0/app/icons/16x16/cil-media-stop.png \
		../cine-encoder-3.0/app/icons/16x16/cil-equalizer.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chat-bubble.png \
		../cine-encoder-3.0/app/icons/16x16/cil-camera.png \
		../cine-encoder-3.0/app/icons/16x16/cil-caret-top.png \
		../cine-encoder-3.0/app/icons/16x16/cil-headphones.png \
		../cine-encoder-3.0/app/icons/16x16/cil-options.png \
		../cine-encoder-3.0/app/icons/16x16/cil-x.png \
		../cine-encoder-3.0/app/icons/16x16/cil-settings.png \
		../cine-encoder-3.0/app/icons/16x16/cil-text.png \
		../cine-encoder-3.0/app/icons/16x16/cil-dialpad.png \
		../cine-encoder-3.0/app/icons/16x16/cil-move.png \
		../cine-encoder-3.0/app/icons/16x16/cil-pen-alt.png \
		../cine-encoder-3.0/app/icons/16x16/cil-save.png \
		../cine-encoder-3.0/app/icons/16x16/cil-low-vision.png \
		../cine-encoder-3.0/app/icons/16x16/cil-arrow-right-.png \
		../cine-encoder-3.0/app/icons/16x16/cil-external-link.png \
		../cine-encoder-3.0/app/icons/16x16/cil-clock.png \
		../cine-encoder-3.0/app/icons/16x16/cil-media-step-backward.png \
		../cine-encoder-3.0/app/icons/16x16/cil-paperclip.png \
		../cine-encoder-3.0/app/icons/16x16/cil-ethernet.png \
		../cine-encoder-3.0/app/icons/16x16/cil-remove.png \
		../cine-encoder-3.0/app/icons/16x16/cil-expand-up.png \
		../cine-encoder-3.0/app/icons/16x16/cil-chevron-top.png \
		../cine-encoder-3.0/app/icons/16x16/cil-camera-roll.png \
		../cine-encoder-3.0/app/icons/16x16/cil-description.png \
		../cine-encoder-3.0/app/icons/16x16/cil-lock-unlocked.png \
		../cine-encoder-3.0/app/icons/16x16/cil-paper-plane.png \
		../cine-encoder-3.0/app/icons/16x16/cil-cloudy.png \
		../cine-encoder-3.0/app/icons/16x16/cil-view-column.png \
		../cine-encoder-3.0/app/icons/16x16/cil-comment-square.png \
		../cine-encoder-3.0/app/icons/16x16/cil-zoom-out.png \
		../cine-encoder-3.0/app/icons/16x16/cil-paragraph.png \
		../cine-encoder-3.0/app/icons/16x16/cil-hdr.png \
		../cine-encoder-3.0/app/icons/16x16/cil-exit-to-app.png \
		../cine-encoder-3.0/app/icons/16x16/cil-movie.png \
		../cine-encoder-3.0/app/icons/16x16/cil-cloud-upload.png \
		../cine-encoder-3.0/app/icons/16x16/cil-media-skip-backward.png \
		../cine-encoder-3.0/app/icons/16x16/cil-user.png \
		../cine-encoder-3.0/app/icons/16x16/cil-check.png \
		../cine-encoder-3.0/app/icons/16x16/cil-screen-desktop.png \
		../cine-encoder-3.0/app/icons/20x20/cil-notes.png \
		../cine-encoder-3.0/app/icons/20x20/cil-volume-high.png \
		../cine-encoder-3.0/app/icons/20x20/cil-media-skip-backward.png \
		../cine-encoder-3.0/app/icons/20x20/cil-power-standby.png \
		../cine-encoder-3.0/app/icons/20x20/cil-speedometer.png \
		../cine-encoder-3.0/app/icons/20x20/cil-vertical-align-bottom.png \
		../cine-encoder-3.0/app/icons/20x20/cil-chart-line.png \
		../cine-encoder-3.0/app/icons/20x20/cil-image-plus.png \
		../cine-encoder-3.0/app/icons/20x20/cil-remove.png \
		../cine-encoder-3.0/app/icons/20x20/cil-user-follow.png \
		../cine-encoder-3.0/app/icons/20x20/cil-file.png \
		../cine-encoder-3.0/app/icons/20x20/cil-trash.png \
		../cine-encoder-3.0/app/icons/20x20/cil-object-ungroup.png \
		../cine-encoder-3.0/app/icons/20x20/cil-speech.png \
		../cine-encoder-3.0/app/icons/20x20/cil-user.png \
		../cine-encoder-3.0/app/icons/20x20/cil-vertical-align-top.png \
		../cine-encoder-3.0/app/icons/20x20/cil-paint-bucket.png \
		../cine-encoder-3.0/app/icons/20x20/cil-check.png \
		../cine-encoder-3.0/app/icons/20x20/cil-video.png \
		../cine-encoder-3.0/app/icons/20x20/cil-comment-bubble.png \
		../cine-encoder-3.0/app/icons/20x20/cil-list.png \
		../cine-encoder-3.0/app/icons/20x20/cil-loop.png \
		../cine-encoder-3.0/app/icons/20x20/cil-loop-circular.png \
		../cine-encoder-3.0/app/icons/20x20/cil-dialpad.png \
		../cine-encoder-3.0/app/icons/20x20/cil-window-minimize.png \
		../cine-encoder-3.0/app/icons/20x20/cil-4k.png \
		../cine-encoder-3.0/app/icons/20x20/cil-airplay.png \
		../cine-encoder-3.0/app/icons/20x20/cil-media-pause.png \
		../cine-encoder-3.0/app/icons/20x20/cil-x-circle.png \
		../cine-encoder-3.0/app/icons/20x20/cil-mug-tea.png \
		../cine-encoder-3.0/app/icons/20x20/cil-options-horizontal.png \
		../cine-encoder-3.0/app/icons/20x20/cil-terminal.png \
		../cine-encoder-3.0/app/icons/20x20/cil-lightbulb.png \
		../cine-encoder-3.0/app/icons/20x20/cil-media-step-backward.png \
		../cine-encoder-3.0/app/icons/20x20/cil-location-pin.png \
		../cine-encoder-3.0/app/icons/20x20/cil-pencil.png \
		../cine-encoder-3.0/app/icons/20x20/cil-image1.png \
		../cine-encoder-3.0/app/icons/20x20/cil-check-circle.png \
		../cine-encoder-3.0/app/icons/20x20/cil-media-step-forward.png \
		../cine-encoder-3.0/app/icons/20x20/cil-fullscreen.png \
		../cine-encoder-3.0/app/icons/20x20/cil-window-restore.png \
		../cine-encoder-3.0/app/icons/20x20/cil-star.png \
		../cine-encoder-3.0/app/icons/20x20/cil-volume-low.png \
		../cine-encoder-3.0/app/icons/20x20/cil-camera-roll.png \
		../cine-encoder-3.0/app/icons/20x20/cil-https.png \
		../cine-encoder-3.0/app/icons/20x20/cil-paperclip.png \
		../cine-encoder-3.0/app/icons/20x20/cil-media-record.png \
		../cine-encoder-3.0/app/icons/20x20/cil-fullscreen-exit.png \
		../cine-encoder-3.0/app/icons/20x20/cil-equalizer.png \
		../cine-encoder-3.0/app/icons/20x20/cil-moon.png \
		../cine-encoder-3.0/app/icons/20x20/cil-plus.png \
		../cine-encoder-3.0/app/icons/20x20/cil-lock-locked.png \
		../cine-encoder-3.0/app/icons/20x20/cil-external-link.png \
		../cine-encoder-3.0/app/icons/20x20/cil-comment-square.png \
		../cine-encoder-3.0/app/icons/20x20/cil-media-play.png \
		../cine-encoder-3.0/app/icons/20x20/cil-link.png \
		../cine-encoder-3.0/app/icons/20x20/cil-home.png \
		../cine-encoder-3.0/app/icons/20x20/cil-code.png \
		../cine-encoder-3.0/app/icons/20x20/cil-link-alt.png \
		../cine-encoder-3.0/app/icons/20x20/cil-paper-plane.png \
		../cine-encoder-3.0/app/icons/20x20/cil-mobile-landscape.png \
		../cine-encoder-3.0/app/icons/20x20/cil-minus.png \
		../cine-encoder-3.0/app/icons/20x20/cil-zoom-in.png \
		../cine-encoder-3.0/app/icons/20x20/cil-headphones.png \
		../cine-encoder-3.0/app/icons/20x20/cil-user-unfollow.png \
		../cine-encoder-3.0/app/icons/20x20/cil-camera.png \
		../cine-encoder-3.0/app/icons/20x20/cil-satelite.png \
		../cine-encoder-3.0/app/icons/20x20/cil-screen-desktop.png \
		../cine-encoder-3.0/app/icons/20x20/cil-settings.png \
		../cine-encoder-3.0/app/icons/20x20/cil-tag.png \
		../cine-encoder-3.0/app/icons/20x20/cil-movie.png \
		../cine-encoder-3.0/app/icons/20x20/cil-media-eject.png \
		../cine-encoder-3.0/app/icons/20x20/cil-media-skip-forward.png \
		../cine-encoder-3.0/app/icons/20x20/cil-people.png \
		../cine-encoder-3.0/app/icons/20x20/cil-description.png \
		../cine-encoder-3.0/app/icons/20x20/cil-3d.png \
		../cine-encoder-3.0/app/icons/20x20/cil-folder.png \
		../cine-encoder-3.0/app/icons/20x20/cil-x.png \
		../cine-encoder-3.0/app/icons/20x20/cil-browser.png \
		../cine-encoder-3.0/app/icons/20x20/cil-chevron-double-up-alt.png \
		../cine-encoder-3.0/app/icons/20x20/cil-zoom-out.png \
		../cine-encoder-3.0/app/icons/20x20/cil-vertical-align-center.png \
		../cine-encoder-3.0/app/icons/20x20/cil-reload.png \
		../cine-encoder-3.0/app/icons/20x20/cil-newspaper.png \
		../cine-encoder-3.0/app/icons/20x20/cil-microphone.png \
		../cine-encoder-3.0/app/icons/20x20/cil-save.png \
		../cine-encoder-3.0/app/icons/20x20/cil-exit-to-app.png \
		../cine-encoder-3.0/app/icons/20x20/cil-cursor.png \
		../cine-encoder-3.0/app/icons/20x20/cil-swap-vertical.png \
		../cine-encoder-3.0/app/icons/20x20/cil-volume-off.png \
		../cine-encoder-3.0/app/icons/20x20/cil-folder-open.png \
		../cine-encoder-3.0/app/icons/20x20/cil-wallpaper.png \
		../cine-encoder-3.0/app/icons/20x20/cil-library-add.png \
		../cine-encoder-3.0/app/icons/20x20/cil-monitor.png \
		../cine-encoder-3.0/app/icons/20x20/cil-task.png \
		../cine-encoder-3.0/app/icons/20x20/cil-library.png \
		../cine-encoder-3.0/app/icons/20x20/cil-copy.png \
		../cine-encoder-3.0/app/icons/20x20/cil-user-female.png \
		../cine-encoder-3.0/app/icons/20x20/cil-media-stop.png \
		../cine-encoder-3.0/app/icons/20x20/cil-check-alt.png \
		../cine-encoder-3.0/app/icons/20x20/cil-options.png \
		../cine-encoder-3.0/app/icons/20x20/cil-music-note.png \
		../cine-encoder-3.0/app/icons/20x20/cil-chevron-bottom.png \
		../cine-encoder-3.0/app/icons/20x20/cil-swap-horizontal.png \
		../cine-encoder-3.0/app/icons/20x20/cil-voice-over-record.png \
		../cine-encoder-3.0/app/icons/20x20/cil-transfer.png \
		../cine-encoder-3.0/app/icons/20x20/cil-menu.png \
		../cine-encoder-3.0/app/icons/20x20/cil-infinity.png \
		../cine-encoder-3.0/app/icons/20x20/cil-input.png \
		../cine-encoder-3.0/app/icons/20x20/cil-mobile.png \
		../cine-encoder-3.0/app/icons/20x20/cil-lock-unlocked.png \
		../cine-encoder-3.0/app/icons/20x20/cil-exposure.png \
		../cine-encoder-3.0/app/icons/20x20/cil-pin.png \
		../cine-encoder-3.0/app/icons/20x20/cil-link-broken.png \
		../cine-encoder-3.0/app/icons/24x24/cil-notes.png \
		../cine-encoder-3.0/app/icons/24x24/cil-volume-high.png \
		../cine-encoder-3.0/app/icons/24x24/cil-media-skip-backward.png \
		../cine-encoder-3.0/app/icons/24x24/cil-power-standby.png \
		../cine-encoder-3.0/app/icons/24x24/cil-speedometer.png \
		../cine-encoder-3.0/app/icons/24x24/cil-vertical-align-bottom.png \
		../cine-encoder-3.0/app/icons/24x24/cil-chart-line.png \
		../cine-encoder-3.0/app/icons/24x24/cil-image-plus.png \
		../cine-encoder-3.0/app/icons/24x24/cil-remove.png \
		../cine-encoder-3.0/app/icons/24x24/cil-user-follow.png \
		../cine-encoder-3.0/app/icons/24x24/cil-file.png \
		../cine-encoder-3.0/app/icons/24x24/cil-trash.png \
		../cine-encoder-3.0/app/icons/24x24/cil-object-ungroup.png \
		../cine-encoder-3.0/app/icons/24x24/cil-speech.png \
		../cine-encoder-3.0/app/icons/24x24/cil-user.png \
		../cine-encoder-3.0/app/icons/24x24/cil-vertical-align-top.png \
		../cine-encoder-3.0/app/icons/24x24/cil-paint-bucket.png \
		../cine-encoder-3.0/app/icons/24x24/cil-check.png \
		../cine-encoder-3.0/app/icons/24x24/cil-video.png \
		../cine-encoder-3.0/app/icons/24x24/cil-comment-bubble.png \
		../cine-encoder-3.0/app/icons/24x24/cil-list.png \
		../cine-encoder-3.0/app/icons/24x24/cil-loop.png \
		../cine-encoder-3.0/app/icons/24x24/cil-loop-circular.png \
		../cine-encoder-3.0/app/icons/24x24/cil-credit-card.png \
		../cine-encoder-3.0/app/icons/24x24/cil-window-minimize.png \
		../cine-encoder-3.0/app/icons/24x24/cil-4k.png \
		../cine-encoder-3.0/app/icons/24x24/cil-airplay.png \
		../cine-encoder-3.0/app/icons/24x24/cil-media-pause.png \
		../cine-encoder-3.0/app/icons/24x24/cil-x-circle.png \
		../cine-encoder-3.0/app/icons/24x24/cil-mug-tea.png \
		../cine-encoder-3.0/app/icons/24x24/cil-options-horizontal.png \
		../cine-encoder-3.0/app/icons/24x24/cil-terminal.png \
		../cine-encoder-3.0/app/icons/24x24/cil-chevron-circle-left-alt.png \
		../cine-encoder-3.0/app/icons/24x24/cil-lightbulb.png \
		../cine-encoder-3.0/app/icons/24x24/cil-media-step-backward.png \
		../cine-encoder-3.0/app/icons/24x24/cil-location-pin.png \
		../cine-encoder-3.0/app/icons/24x24/cil-pencil.png \
		../cine-encoder-3.0/app/icons/24x24/cil-image1.png \
		../cine-encoder-3.0/app/icons/24x24/cil-check-circle.png \
		../cine-encoder-3.0/app/icons/24x24/cil-media-step-forward.png \
		../cine-encoder-3.0/app/icons/24x24/cil-fullscreen.png \
		../cine-encoder-3.0/app/icons/24x24/cil-window-restore.png \
		../cine-encoder-3.0/app/icons/24x24/cil-star.png \
		../cine-encoder-3.0/app/icons/24x24/cil-volume-low.png \
		../cine-encoder-3.0/app/icons/24x24/cil-move.png \
		../cine-encoder-3.0/app/icons/24x24/cil-camera-roll.png \
		../cine-encoder-3.0/app/icons/24x24/cil-https.png \
		../cine-encoder-3.0/app/icons/24x24/cil-paperclip.png \
		../cine-encoder-3.0/app/icons/24x24/cil-media-record.png \
		../cine-encoder-3.0/app/icons/24x24/cil-fullscreen-exit.png \
		../cine-encoder-3.0/app/icons/24x24/cil-equalizer.png \
		../cine-encoder-3.0/app/icons/24x24/cil-moon.png \
		../cine-encoder-3.0/app/icons/24x24/cil-plus.png \
		../cine-encoder-3.0/app/icons/24x24/cil-lock-locked.png \
		../cine-encoder-3.0/app/icons/24x24/cil-external-link.png \
		../cine-encoder-3.0/app/icons/24x24/cil-comment-square.png \
		../cine-encoder-3.0/app/icons/24x24/cil-media-play.png \
		../cine-encoder-3.0/app/icons/24x24/cil-link.png \
		../cine-encoder-3.0/app/icons/24x24/cil-home.png \
		../cine-encoder-3.0/app/icons/24x24/cil-code.png \
		../cine-encoder-3.0/app/icons/24x24/cil-link-alt.png \
		../cine-encoder-3.0/app/icons/24x24/cil-paper-plane.png \
		../cine-encoder-3.0/app/icons/24x24/cil-mobile-landscape.png \
		../cine-encoder-3.0/app/icons/24x24/cil-minus.png \
		../cine-encoder-3.0/app/icons/24x24/cil-zoom-in.png \
		../cine-encoder-3.0/app/icons/24x24/cil-headphones.png \
		../cine-encoder-3.0/app/icons/24x24/cil-user-unfollow.png \
		../cine-encoder-3.0/app/icons/24x24/cil-camera.png \
		../cine-encoder-3.0/app/icons/24x24/cil-chevron-circle-up-alt.png \
		../cine-encoder-3.0/app/icons/24x24/cil-satelite.png \
		../cine-encoder-3.0/app/icons/24x24/cil-screen-desktop.png \
		../cine-encoder-3.0/app/icons/24x24/cil-settings.png \
		../cine-encoder-3.0/app/icons/24x24/cil-tag.png \
		../cine-encoder-3.0/app/icons/24x24/cil-movie.png \
		../cine-encoder-3.0/app/icons/24x24/cil-media-eject.png \
		../cine-encoder-3.0/app/icons/24x24/cil-media-skip-forward.png \
		../cine-encoder-3.0/app/icons/24x24/cil-people.png \
		../cine-encoder-3.0/app/icons/24x24/cil-description.png \
		../cine-encoder-3.0/app/icons/24x24/cil-3d.png \
		../cine-encoder-3.0/app/icons/24x24/cil-folder.png \
		../cine-encoder-3.0/app/icons/24x24/cil-x.png \
		../cine-encoder-3.0/app/icons/24x24/cil-browser.png \
		../cine-encoder-3.0/app/icons/24x24/cil-chevron-double-up-alt.png \
		../cine-encoder-3.0/app/icons/24x24/cil-zoom-out.png \
		../cine-encoder-3.0/app/icons/24x24/cil-vertical-align-center.png \
		../cine-encoder-3.0/app/icons/24x24/cil-chevron-circle-right-alt.png \
		../cine-encoder-3.0/app/icons/24x24/cil-reload.png \
		../cine-encoder-3.0/app/icons/24x24/cil-microphone.png \
		../cine-encoder-3.0/app/icons/24x24/cil-newspaper.png \
		../cine-encoder-3.0/app/icons/24x24/cil-save.png \
		../cine-encoder-3.0/app/icons/24x24/cil-exit-to-app.png \
		../cine-encoder-3.0/app/icons/24x24/cil-cursor.png \
		../cine-encoder-3.0/app/icons/24x24/cil-swap-vertical.png \
		../cine-encoder-3.0/app/icons/24x24/cil-volume-off.png \
		../cine-encoder-3.0/app/icons/24x24/cil-folder-open.png \
		../cine-encoder-3.0/app/icons/24x24/cil-wallpaper.png \
		../cine-encoder-3.0/app/icons/24x24/cil-library-add.png \
		../cine-encoder-3.0/app/icons/24x24/cil-monitor.png \
		../cine-encoder-3.0/app/icons/24x24/cil-task.png \
		../cine-encoder-3.0/app/icons/24x24/cil-library.png \
		../cine-encoder-3.0/app/icons/24x24/cil-copy.png \
		../cine-encoder-3.0/app/icons/24x24/cil-user-female.png \
		../cine-encoder-3.0/app/icons/24x24/cil-media-stop.png \
		../cine-encoder-3.0/app/icons/24x24/cil-check-alt.png \
		../cine-encoder-3.0/app/icons/24x24/cil-options.png \
		../cine-encoder-3.0/app/icons/24x24/cil-chevron-bottom.png \
		../cine-encoder-3.0/app/icons/24x24/cil-music-note.png \
		../cine-encoder-3.0/app/icons/24x24/cil-swap-horizontal.png \
		../cine-encoder-3.0/app/icons/24x24/cil-voice-over-record.png \
		../cine-encoder-3.0/app/icons/24x24/cil-transfer.png \
		../cine-encoder-3.0/app/icons/24x24/cil-menu.png \
		../cine-encoder-3.0/app/icons/24x24/cil-infinity.png \
		../cine-encoder-3.0/app/icons/24x24/cil-input.png \
		../cine-encoder-3.0/app/icons/24x24/cine-encoder.png \
		../cine-encoder-3.0/app/icons/24x24/cil-mobile.png \
		../cine-encoder-3.0/app/icons/24x24/cil-lock-unlocked.png \
		../cine-encoder-3.0/app/icons/24x24/cil-exposure.png \
		../cine-encoder-3.0/app/icons/24x24/cil-pin.png \
		../cine-encoder-3.0/app/icons/24x24/cil-link-broken.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-notes.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-volume-high.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-media-skip-backward.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-power-standby.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-speedometer.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-chart-line.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-image-plus.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-remove.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-user-follow.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-file.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-object-ungroup.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-speech.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-user.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-paint-bucket.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-check.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-comment-bubble.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-list.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-loop.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-loop-circular.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-dialpad.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-credit-card.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-window-minimize.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-4k.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-airplay.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-media-pause.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-mug-tea.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-options-horizontal.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-lightbulb.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-media-step-backward.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-location-pin.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-pencil.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-image1.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-check-circle.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-media-step-forward.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-fullscreen.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-window-restore.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-star.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-volume-low.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-move.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-camera-roll.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-https.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-paperclip.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-media-record.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-fullscreen-exit.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-equalizer.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-plus.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-lock-locked.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-external-link.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-comment-square.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-media-play.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-link.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-home.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-code.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-cursor-move.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-link-alt.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-paper-plane.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-mobile-landscape.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-minus.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-zoom-in.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-headphones.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-user-unfollow.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-camera.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-satelite.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-screen-desktop.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-settings.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-tag.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-movie.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-media-eject.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-media-skip-forward.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-people.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-description.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-3d.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-folder.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-x.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-browser.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-chevron-double-up-alt.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-zoom-out.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-reload.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-microphone.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-newspaper.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-save.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-exit-to-app.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-cursor.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-swap-vertical.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-volume-off.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-folder-open.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-wallpaper.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-library-add.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-monitor.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-task.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-library.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-copy.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-user-female.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-media-stop.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-check-alt.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-options.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-chevron-bottom.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-music-note.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-wallet.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-swap-horizontal.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-voice-over-record.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-transfer.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-menu.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-infinity.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-input.png \
		../cine-encoder-3.0/app/icons/Apagar/cine-encoder.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-mobile.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-lock-unlocked.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-exposure.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-pin.png \
		../cine-encoder-3.0/app/icons/Apagar/cil-link-broken.png
	/usr/bin/rcc -name files ../cine-encoder-3.0/app/files.qrc -o qrc_files.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_about.cpp moc_mainwindow.cpp moc_preset.cpp moc_selectpreset.cpp moc_settings.cpp moc_taskcomplete.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_about.cpp moc_mainwindow.cpp moc_preset.cpp moc_selectpreset.cpp moc_settings.cpp moc_taskcomplete.cpp
moc_about.cpp: ../cine-encoder-3.0/app/about.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/build-cine_encoder-Desktop-Debug/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/cine-encoder-3.0/app -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include ../cine-encoder-3.0/app/about.h -o moc_about.cpp

moc_mainwindow.cpp: ../cine-encoder-3.0/app/mainwindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/build-cine_encoder-Desktop-Debug/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/cine-encoder-3.0/app -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include ../cine-encoder-3.0/app/mainwindow.h -o moc_mainwindow.cpp

moc_preset.cpp: ../cine-encoder-3.0/app/preset.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/build-cine_encoder-Desktop-Debug/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/cine-encoder-3.0/app -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include ../cine-encoder-3.0/app/preset.h -o moc_preset.cpp

moc_selectpreset.cpp: ../cine-encoder-3.0/app/selectpreset.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/build-cine_encoder-Desktop-Debug/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/cine-encoder-3.0/app -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include ../cine-encoder-3.0/app/selectpreset.h -o moc_selectpreset.cpp

moc_settings.cpp: ../cine-encoder-3.0/app/settings.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/build-cine_encoder-Desktop-Debug/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/cine-encoder-3.0/app -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include ../cine-encoder-3.0/app/settings.h -o moc_settings.cpp

moc_taskcomplete.cpp: ../cine-encoder-3.0/app/taskcomplete.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/build-cine_encoder-Desktop-Debug/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/run/media/helg/GOODRAM-SDB/QtCreatorProjects/CineEncoder/cine-encoder-3.0/app -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include ../cine-encoder-3.0/app/taskcomplete.h -o moc_taskcomplete.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_about.h ui_mainwindow.h ui_preset.h ui_selectpreset.h ui_settings.h ui_taskcomplete.h
compiler_uic_clean:
	-$(DEL_FILE) ui_about.h ui_mainwindow.h ui_preset.h ui_selectpreset.h ui_settings.h ui_taskcomplete.h
ui_about.h: ../cine-encoder-3.0/app/about.ui \
		/usr/bin/uic
	/usr/bin/uic ../cine-encoder-3.0/app/about.ui -o ui_about.h

ui_mainwindow.h: ../cine-encoder-3.0/app/mainwindow.ui \
		/usr/bin/uic
	/usr/bin/uic ../cine-encoder-3.0/app/mainwindow.ui -o ui_mainwindow.h

ui_preset.h: ../cine-encoder-3.0/app/preset.ui \
		/usr/bin/uic
	/usr/bin/uic ../cine-encoder-3.0/app/preset.ui -o ui_preset.h

ui_selectpreset.h: ../cine-encoder-3.0/app/selectpreset.ui \
		/usr/bin/uic
	/usr/bin/uic ../cine-encoder-3.0/app/selectpreset.ui -o ui_selectpreset.h

ui_settings.h: ../cine-encoder-3.0/app/settings.ui \
		/usr/bin/uic
	/usr/bin/uic ../cine-encoder-3.0/app/settings.ui -o ui_settings.h

ui_taskcomplete.h: ../cine-encoder-3.0/app/taskcomplete.ui \
		/usr/bin/uic
	/usr/bin/uic ../cine-encoder-3.0/app/taskcomplete.ui -o ui_taskcomplete.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

about.o: ../cine-encoder-3.0/app/about.cpp ../cine-encoder-3.0/app/about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o ../cine-encoder-3.0/app/about.cpp

main.o: ../cine-encoder-3.0/app/main.cpp ../cine-encoder-3.0/app/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../cine-encoder-3.0/app/main.cpp

mainwindow.o: ../cine-encoder-3.0/app/mainwindow.cpp ../cine-encoder-3.0/app/mainwindow.h \
		ui_mainwindow.h \
		../cine-encoder-3.0/app/about.h \
		../cine-encoder-3.0/app/settings.h \
		../cine-encoder-3.0/app/selectpreset.h \
		../cine-encoder-3.0/app/taskcomplete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../cine-encoder-3.0/app/mainwindow.cpp

preset.o: ../cine-encoder-3.0/app/preset.cpp ../cine-encoder-3.0/app/preset.h \
		ui_preset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preset.o ../cine-encoder-3.0/app/preset.cpp

selectpreset.o: ../cine-encoder-3.0/app/selectpreset.cpp ../cine-encoder-3.0/app/preset.h \
		../cine-encoder-3.0/app/selectpreset.h \
		ui_selectpreset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectpreset.o ../cine-encoder-3.0/app/selectpreset.cpp

settings.o: ../cine-encoder-3.0/app/settings.cpp ../cine-encoder-3.0/app/settings.h \
		ui_settings.h \
		../cine-encoder-3.0/app/taskcomplete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o ../cine-encoder-3.0/app/settings.cpp

taskcomplete.o: ../cine-encoder-3.0/app/taskcomplete.cpp ../cine-encoder-3.0/app/taskcomplete.h \
		ui_taskcomplete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskcomplete.o ../cine-encoder-3.0/app/taskcomplete.cpp

qrc_files.o: qrc_files.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_files.o qrc_files.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_preset.o: moc_preset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preset.o moc_preset.cpp

moc_selectpreset.o: moc_selectpreset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selectpreset.o moc_selectpreset.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_taskcomplete.o: moc_taskcomplete.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskcomplete.o moc_taskcomplete.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

