.\" Man page for cine_encoder
.\" Contact depositmail@rambler.ru
.TH CineEncoder 2021 "09 Feb 2021"
.SH NAME
CineEncoder \- Video Encoder
.SH SYNOPSIS
CineEncoder is a video encoder based on Qt and C++.
.SH DESCRIPTION
 Cine Encoder is an application that allows you to convert media
 files while preserving HDR metadata. NVENC hardware encoding for 
 NVIDIA video cards is also supported for H265 and H264 modes.
 It is licensed under GPLv3.
.SH OPTIONS
No options for this man page
.SH SEE ALSO
man(1), groff(1), man.config(5)
.SH BUGS
If you find a bug, please report it at below address.
.SH AUTHOR
Oleg Kozhukharenko (depositmail@rambler.ru)
